#!/usr/bin/env python3
"""Write the section-colour rules into components.css between managed markers.

    python3 tools/build_sections_css.py

Idempotent: the block is replaced, never appended twice.
"""

import os, re, sys
import sections as S

START = '/* >>> section-colours (generated by tools/build_sections_css.py) */'
END = '/* <<< section-colours */'


def main():
    if not os.path.exists('index.html'):
        sys.exit('run this from the site root')
    p = 'assets/css/components.css'
    css = open(p, encoding='utf-8').read()
    block = f'{START}\n{S.css_block()}{END}\n'
    if START in css:
        css = re.sub(re.escape(START) + r'.*?' + re.escape(END) + r'\n',
                     lambda m: block, css, flags=re.S)
    else:
        css = css.rstrip('\n') + '\n\n' + block
    open(p, 'w', encoding='utf-8').write(css)
    print(f'  components.css  {len(S.COLOURS)} section colours')


if __name__ == '__main__':
    main()
